version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node -v
  pre_build:
    commands:
      - yarn -v
      - yarn install --network-timeout 1000000 --production=false
  build:
    commands:
      - yarn run generate
      - rm ./dist/_nuxt/LICENSES
      - aws s3 sync　./dist s3://${FRONTEND_BUCKET}/ --delete
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
