AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Env:
    Type: String
    Default: "development"
  GitHubUser:
    Type: String
  GitHubToken:
    Type: String
  GitHubBranch:
    Type: String
    Default: "master"
  ApiKey:
    Type: String
  LambdaArn:
    Type: String
    Default: ""
  Domain:
    Type: String
    Default: "rcanai.jp"
  FullDomain:
    Type: String
    Default: "dev-simple-ssl-nuxt.rcanai.jp"

# 条件
Conditions:
  # Basic認証の有無
  HasLambda: !Not [!Equals [!Ref LambdaArn, "" ]]

Resources:
  # ------
  # S3 Deploy Bucket
  # ------
  DeployS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "simple-sls-nuxt-deploy"

  # ------
  # IAM Role (CodeBuild)
  # ------
  DeployCodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-codebuild"
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - "apigateway:*"
                  - "cloudformation:*"
                  - "cloudfront:*"
                  - "execute-api:Invoke"
                  - "iam:*"
                  - "lambda:*"
                  - "logs:*"
                  - "s3:*"
  # ------
  # IAM Role (CodePipeline)
  # ------
  DeployCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-codepipeline"
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: !Sub "arn:aws:s3:::${DeployS3Bucket}/*"
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
              - Resource: "*"
                Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - iam:PassRole

  # ------
  # CodeBuild
  # ------
  DeployCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: "aws/buildspec.yml"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: NODE_ENV
            Value: !Ref Env
          - Name: API_KEY
            Value: !Ref ApiKey
          - Name: LAMBDA_ARN
            Value: !Ref LambdaArn
          - Name: HAS_LAMBDA
            Value: !If
              - HasLambda
              - true
              - false
          - Name: DOMAIN
            Value: !Ref Domain
          - Name: FULL_DOMAIN
            Value: !Ref FullDomain
      Name: !Sub "${AWS::StackName}-codebuild"
      ServiceRole: !Ref DeployCodeBuildServiceRole
      QueuedTimeoutInMinutes: 15
      TimeoutInMinutes: 10

  # ------
  # CodePipeline
  # ------
  DeployCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${AWS::StackName}-codepipeline"
      RoleArn: !GetAtt DeployCodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref DeployS3Bucket
      Stages:
        - Name: Source
          Actions:
            - Name: App
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubUser
                Repo: "simple-sls-nuxt"
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: App
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref DeployCodeBuildProject
              InputArtifacts:
                - Name: App
              RunOrder: 1

  # ------
  # CodePipeline Webhook
  # ------
  DeployPipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubToken
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: "refs/heads/{Branch}"
      TargetPipeline: !Ref DeployCodePipeline
      TargetAction: App
      Name: !Sub "${AWS::StackName}-codepipeline-webhook"
      TargetPipelineVersion: !GetAtt DeployCodePipeline.Version
      RegisterWithThirdParty: true

Outputs:
  SimpleSlsNuxtApiKey:
    Value: !Ref ApiKey
    Export:
      Name: SimpleSlsNuxtApiKey
