AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SlsStage:
    Type: String
  SlsApiId:
    Type: String
  ApiKey:
    Type: String

Resources:
  # ------
  # Cloud Front
  # ------
  SimpleSlsNuxtCFDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Alias(CNAMEs)の設定はSSL証明書の設定が必要
        # Aliases:
        #   - "simple-sls-nuxt.rcanai.com"
        Origins:
          - Id: SimpleSlsNuxtAPIGW
            DomainName: !Sub "${SlsApiId}.execute-api.ap-northeast-1.amazonaws.com"
            OriginPath: !Sub "/${SlsStage}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "match-viewer"
            OriginCustomHeaders:
              - HeaderName: "X-API-KEY"
                HeaderValue: !Ref ApiKey
          # - Id: SimpleSlsNuxtStaticBucket
          #   DomainName: !Sub "${SlsStage}-simple-sls-nuxt-static-bucket"
          #   OriginPath: ""
          #   S3OriginConfig:
          #     OriginAccessIdentity: ""
        Enabled: true
        HttpVersion: "http1.1"
        Comment:
          Ref: AWS::StackName
        DefaultRootObject: ""
        DefaultCacheBehavior:
          TargetOriginId: SimpleSlsNuxtAPIGW
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
