AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SlsStage:
    Type: String
  SlsApiId:
    Type: String
  SSLArn:
    Type: String

Resources:
  # ------
  # Cloud Front
  # ------
  SimpleSlsNuxtCFDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Alias(CNAMEs)の設定はSSL証明書の設定が必要
        Aliases:
          - "simple-sls-nuxt.rcanai.com"
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLArn
          MinimumProtocolVersion: TLSv1_2016 # 現時点でのRecommended
          SslSupportMethod: sni-only
        Origins:
          - Id: SimpleSlsNuxtAPIGW
            DomainName: !Sub "${SlsApiId}.execute-api.ap-northeast-1.amazonaws.com"
            OriginPath: !Sub "/${SlsStage}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: match-viewer
            OriginCustomHeaders:
              - HeaderName: "X-API-KEY"
                HeaderValue: !ImportValue SimpleSlsNuxtApiKey
          - Id: SimpleSlsNuxtStaticS3Bucket
            DomainName: !ImportValue SimpleSlsNuxtStaticS3BucketDomainName
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - "origin-access-identity/cloudfront/"
                    - Fn::ImportValue: SimpleSlsNuxtCFOriginAccessIdentity
        Enabled: true
        HttpVersion: http2 # SSL証明書が必要
        Comment:
          Ref: AWS::StackName
        DefaultRootObject: ""
        DefaultCacheBehavior:
          TargetOriginId: SimpleSlsNuxtAPIGW
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: all
          Compress: true
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
        CacheBehaviors:
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/favicon.ico"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/sw.js"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/*.png"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/_nuxt/images/*"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 0
            ResponseCode: 404
            ResponsePagePath: "/404"
  # ------
  # Route53 RecordSet
  # ------
  SimpleSlsNuxtRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: rcanai.com.
      Name: simple-sls-nuxt.rcanai.com.
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFrontなのでIDは固定
        DNSName: !GetAtt SimpleSlsNuxtCFDist.DomainName
