AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SlsStage:
    Type: String
  SlsApiId:
    Type: String

Resources:
  # ------
  # Cloud Front
  # ------
  SimpleSlsNuxtCFDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Alias(CNAMEs)の設定はSSL証明書の設定が必要
        # Aliases:
        #   - "simple-sls-nuxt.rcanai.com"
        Origins:
          - Id: SimpleSlsNuxtAPIGW
            DomainName: !Sub "${SlsApiId}.execute-api.ap-northeast-1.amazonaws.com"
            OriginPath: !Sub "/${SlsStage}"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "match-viewer"
            OriginCustomHeaders:
              - HeaderName: "X-API-KEY"
                HeaderValue: !ImportValue SimpleSlsNuxtApiKey
          - Id: SimpleSlsNuxtStaticS3Bucket
            DomainName: !ImportValue SimpleSlsNuxtStaticS3BucketDomainName
            OriginPath: ""
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - ""
                  - - "origin-access-identity/cloudfront/"
                    - Fn::ImportValue: SimpleSlsNuxtCFOriginAccessIdentity
        Enabled: true
        HttpVersion: "http1.1"
        Comment:
          Ref: AWS::StackName
        DefaultRootObject: ""
        DefaultCacheBehavior:
          TargetOriginId: SimpleSlsNuxtAPIGW
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: all
          Compress: true
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
        CacheBehaviors:
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/favicon.ico"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/sw.js"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/*.png"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
          - TargetOriginId: SimpleSlsNuxtStaticS3Bucket
            PathPattern: "/_nuxt/images/*"
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: false
            Compress: true
